export const limbs = [
  {
    n: 1,
    sanskrit: 'Yama',
    translation: 'Restricciones éticas',
    icon: '🤝',
    color: 'rose',
    tagline: 'Cómo nos relacionamos con el mundo que nos rodea.',
    description:
      'El primer peldaño mira hacia afuera: es el código ético que rige nuestro trato con los demás seres. Antes de transformar el cuerpo o la mente, el yoga pide honestidad en la forma de habitar el mundo.',
    practices: [
      'Ahimsa — no violencia, en el pensamiento, la palabra y la acción.',
      'Satya — verdad, decir y vivir con honestidad.',
      'Asteya — no robar, ni objetos ni tiempo ni crédito ajeno.',
      'Brahmacharya — moderación de la energía vital y los sentidos.',
      'Aparigraha — no acumular más de lo necesario, soltar el apego.',
    ],
    quote: '“La no violencia es la más alta de las virtudes.” — Yoga Sutras de Patañjali',
  },
  {
    n: 2,
    sanskrit: 'Niyama',
    translation: 'Observancias personales',
    icon: '🪷',
    color: 'amber',
    tagline: 'Cómo nos relacionamos con nosotros mismos.',
    description:
      'Si Yama ordena el mundo exterior, Niyama ordena el mundo interior: disciplinas personales que cultivan claridad, contento y disciplina como base para el trabajo más sutil que vendrá.',
    practices: [
      'Saucha — pureza, limpieza del cuerpo y de la mente.',
      'Santosha — contento genuino con lo que es, aquí y ahora.',
      'Tapas — disciplina y calor interior, el fuego de la constancia.',
      'Svadhyaya — autoestudio, observarse con honestidad.',
      'Ishvara Pranidhana — entrega a algo más grande que el yo.',
    ],
    quote: '“El contento trae una felicidad incomparable.” — Yoga Sutras de Patañjali',
  },
  {
    n: 3,
    sanskrit: 'Asana',
    translation: 'Postura física',
    icon: '🧘',
    color: 'teal',
    tagline: 'Un asiento estable y cómodo para el cuerpo.',
    description:
      'La rama más conocida en Occidente, pero originalmente pensada como una sola cosa: un asiento firme y agradable para poder sentarse en meditación durante largo tiempo. Con los siglos floreció en el vasto repertorio de posturas que hoy conocemos.',
    practices: [
      'Firmeza (sthira) sin rigidez, comodidad (sukha) sin flojera.',
      'Explorar el límite del cuerpo con atención, no con violencia.',
      'Usar la postura como espejo del estado mental.',
      'Preparar el cuerpo para permanecer inmóvil en la quietud.',
    ],
    quote: '“Sthira sukham asanam: la postura es firmeza y comodidad.” — Yoga Sutras de Patañjali',
  },
  {
    n: 4,
    sanskrit: 'Pranayama',
    translation: 'Control de la energía vital',
    icon: '🌬️',
    color: 'cyan',
    tagline: 'La respiración como puente entre cuerpo y mente.',
    description:
      'Prana es la fuerza vital; ayama, su extensión y control. Al regular conscientemente el ritmo de la respiración —inhalación, retención, exhalación— se calma el sistema nervioso y se abre la puerta hacia estados más sutiles de conciencia.',
    practices: [
      'Observar la respiración natural antes de modificarla.',
      'Alargar la exhalación para activar la calma.',
      'Prácticas como Nadi Shodhana o Ujjayi como puente hacia adentro.',
      'La retención (kumbhaka) como umbral de quietud total.',
    ],
    quote: '“Cuando la respiración se aquieta, la mente se aquieta.” — enseñanza tradicional del hatha yoga',
  },
  {
    n: 5,
    sanskrit: 'Pratyahara',
    translation: 'Retiro de los sentidos',
    icon: '🕯️',
    color: 'violet',
    tagline: 'Girar la mirada de afuera hacia adentro.',
    description:
      'La primera de las cuatro ramas internas. Los sentidos dejan de perseguir estímulos externos y la atención se retrae, como una tortuga que recoge sus extremidades. No es negar el mundo sensorial, sino dejar de ser arrastrado por él.',
    practices: [
      'Notar un estímulo sin perseguirlo ni rechazarlo.',
      'Practicar en penumbra, silencio o con los ojos cerrados.',
      'Soltar, uno a uno, el sonido, la imagen, el tacto, el pensamiento.',
      'Encontrar quietud incluso en medio del ruido cotidiano.',
    ],
    quote: '“Cuando los sentidos se apartan de sus objetos, surge Pratyahara.” — Yoga Sutras de Patañjali',
  },
  {
    n: 6,
    sanskrit: 'Dharana',
    translation: 'Concentración',
    icon: '🎯',
    color: 'indigo',
    tagline: 'Fijar la mente en un solo punto.',
    description:
      'Con los sentidos ya recogidos, la mente aprende a posarse en un único objeto —la respiración, una llama, un mantra, un punto entre las cejas— sosteniendo la atención sin dispersarse. Es el entrenamiento directo de la voluntad.',
    practices: [
      'Elegir un ancla: respiración, mantra, imagen o punto fijo.',
      'Volver una y otra vez, sin frustración, cuando la mente divaga.',
      'Sesiones breves y frecuentes antes que largas y forzadas.',
      'Notar el espacio entre un pensamiento y el siguiente.',
    ],
    quote: '“Dharana es fijar la mente en un solo lugar.” — Yoga Sutras de Patañjali',
  },
  {
    n: 7,
    sanskrit: 'Dhyana',
    translation: 'Meditación',
    icon: '🌌',
    color: 'fuchsia',
    tagline: 'Un flujo ininterrumpido de atención.',
    description:
      'Cuando la concentración se sostiene sin esfuerzo y sin cortes, Dharana madura en Dhyana: un flujo continuo de conciencia hacia el objeto, sin que el pensamiento del “yo que medito” interrumpa la experiencia.',
    practices: [
      'Dejar que la atención se sostenga sola, sin forzarla.',
      'Soltar la distinción entre observador y observado.',
      'Permitir que los pensamientos pasen como nubes, sin aferrarse.',
      'Cultivar la constancia diaria más que la intensidad puntual.',
    ],
    quote: '“Dhyana es la continuidad ininterrumpida de esa atención.” — Yoga Sutras de Patañjali',
  },
  {
    n: 8,
    sanskrit: 'Samadhi',
    translation: 'Unión, absorción total',
    icon: '✨',
    color: 'emerald',
    tagline: 'La disolución del yo en aquello que se contempla.',
    description:
      'La culminación del camino: el meditador, la meditación y lo meditado se funden en una sola experiencia. Ya no hay separación entre quien observa y lo observado. Es el estado de unión, plenitud y silencio absoluto del ser.',
    practices: [
      'No se “practica” Samadhi: se cultivan las siete ramas anteriores.',
      'Se reconoce por la ausencia de esfuerzo y de separación.',
      'Puede visitarse brevemente antes de estabilizarse con el tiempo.',
      'Es fruto, no técnica: la maduración natural del camino completo.',
    ],
    quote: '“En ese estado, solo brilla el objeto, vacío de forma propia.” — Yoga Sutras de Patañjali',
  },
];
