export const darshanas = [
  {
    id: 'nyaya',
    group: 'astika',
    name: 'Nyaya',
    note: 'Lógica',
    icon: '⚖️',
    founder: 'Gautama (Akshapada)',
    text: 'Nyaya Sutras',
    era: 'c. siglo II a.C.',
    summary:
      'La escuela de la razón y el debate. Busca el conocimiento correcto (pramana) como camino para liberarse del sufrimiento.',
    ideas: [
      'Cuatro fuentes válidas de conocimiento: percepción, inferencia, comparación y testimonio fiable.',
      'Método de análisis en cinco pasos (tesis, razón, ejemplo, aplicación, conclusión), antecedente de la lógica formal india.',
      'Detectar las falacias es parte del camino: pensar mal también encadena.',
    ],
    yogaLink: 'Aporta el rigor: discernir lo real de lo imaginado es la base del viveka (discernimiento) en el yoga.',
    color: 'sky',
  },
  {
    id: 'vaisheshika',
    group: 'astika',
    name: 'Vaisheshika',
    note: 'Atomismo',
    icon: '⚛️',
    founder: 'Kanada',
    text: 'Vaisheshika Sutras',
    era: 'c. siglo II a.C.',
    summary:
      'Una física filosófica: describe la realidad como un conjunto de categorías (padarthas) y la materia como compuesta de átomos (paramanu).',
    ideas: [
      'Seis categorías: sustancia, cualidad, acción, universalidad, particularidad e inherencia (más tarde, ausencia).',
      'Los elementos (tierra, agua, fuego, aire) están formados por átomos eternos.',
      'Funciona en pareja con Nyaya: una describe qué existe, la otra cómo conocerlo.',
    ],
    yogaLink: 'Ayuda a entender el cuerpo y los elementos (bhutas) con los que el yoga trabaja.',
    color: 'cyan',
  },
  {
    id: 'sankhya',
    group: 'astika',
    name: 'Sankhya',
    note: 'Enumeración',
    icon: '🔢',
    founder: 'Kapila (tradición)',
    text: 'Sankhya Karika, de Ishvarakrishna',
    era: 'Raíces antiguas; texto clásico c. siglo IV d.C.',
    summary:
      'Una filosofía dualista que enumera 25 principios (tattvas). Todo lo que existe nace de la unión de dos realidades: Purusha y Prakriti.',
    ideas: [
      'Purusha: la conciencia pura, testigo inmóvil.',
      'Prakriti: la naturaleza, que incluye cuerpo, mente y mundo.',
      'Los tres gunas: sattva (claridad), rajas (movimiento) y tamas (inercia).',
      'El sufrimiento surge de confundir al testigo con lo que observa.',
    ],
    yogaLink: 'Es la base teórica del yoga de Patanjali: Sankhya explica el mapa, el yoga ofrece la práctica para recorrerlo.',
    color: 'violet',
  },
  {
    id: 'yoga',
    group: 'astika',
    name: 'Yoga',
    note: 'Disciplina',
    icon: '🧘',
    founder: 'Patanjali (sistematizador)',
    text: 'Yoga Sutras',
    era: 'c. 200 a.C. – 400 d.C.',
    summary:
      'La escuela práctica. Toma el mapa del Sankhya y añade un método: ocho ramas para aquietar la mente y reconocer al testigo.',
    ideas: [
      'Yogas chitta vritti nirodhah: yoga es aquietar las fluctuaciones de la mente.',
      'Ashtanga: yama, niyama, asana, pranayama, pratyahara, dharana, dhyana y samadhi.',
      'Añade a Ishvara, un principio divino como objeto de devoción, algo que el Sankhya clásico no tenía.',
    ],
    yogaLink: 'Es el tema de esta página.',
    link: { href: '/yoga/ocho_ramas_del_yoga', label: 'Ver las 8 ramas del yoga →' },
    color: 'indigo',
  },
  {
    id: 'mimamsa',
    group: 'astika',
    name: 'Mimamsa',
    note: 'Ritual',
    icon: '🔥',
    founder: 'Jaimini',
    text: 'Mimamsa Sutras',
    era: 'c. siglo III a.C.',
    summary:
      'La "investigación" de la parte ritual de los Vedas. Sostiene que el deber (dharma) se cumple a través de la acción correcta.',
    ideas: [
      'El Veda se considera eterno y sin autor humano (apaurusheya).',
      'Hace de la interpretación de los textos una ciencia, con reglas propias de lectura.',
      'Importa el acto bien ejecutado y el sonido exacto de la palabra sagrada.',
    ],
    yogaLink: 'Su cuidado del sonido y del acto consciente resuena en el mantra y en el karma yoga.',
    color: 'amber',
  },
  {
    id: 'vedanta',
    group: 'astika',
    name: 'Vedanta',
    note: 'No dualidad',
    icon: '🌅',
    founder: 'Badarayana; Shankara (Advaita)',
    text: 'Brahma Sutras y Upanishads',
    era: 'Raíces upanishádicas; Shankara, c. siglo VIII d.C.',
    summary:
      '"El fin de los Vedas". Recoge la enseñanza de los Upanishads: el Ser individual (Atman) y la realidad última (Brahman) no son distintos.',
    ideas: [
      'Advaita (no dualidad): Atman es Brahman; la separación es una ilusión (maya).',
      'Otras ramas —Vishishtadvaita, Dvaita— matizan o niegan esa identidad total.',
      'La liberación (moksha) es un reconocimiento, no una conquista.',
    ],
    yogaLink: 'Muchos maestros modernos de yoga entienden la meta del samadhi en clave vedántica.',
    link: { href: '#upanishads', label: 'Ver Upanishads en la línea de tiempo ↓' },
    color: 'rose',
  },
  {
    id: 'charvaka',
    group: 'nastika',
    name: 'Charvaka',
    note: 'Materialismo',
    icon: '🍃',
    founder: 'Brihaspati (tradición)',
    text: 'Se conserva solo en citas de sus críticos',
    era: 'c. siglo VI a.C.',
    summary:
      'La escuela materialista y escéptica. Solo acepta la percepción como fuente de conocimiento; rechaza los Vedas, el karma y la vida después de la muerte.',
    ideas: [
      'Existe únicamente lo que se percibe: el cuerpo es la persona, la conciencia surge de la materia.',
      'No hay renacimiento ni liberación: el objetivo es vivir bien aquí.',
      'Su existencia muestra que la India antigua debatía incluso la negación de lo espiritual.',
    ],
    yogaLink: 'Es el contrapunto: las demás escuelas se definen en parte respondiéndole.',
    color: 'emerald',
  },
  {
    id: 'jainismo',
    group: 'nastika',
    name: 'Jainismo',
    note: 'Ahimsa',
    icon: '🕊️',
    founder: 'Mahavira (24.º tirthankara)',
    text: 'Agamas',
    era: 'c. siglo VI a.C.',
    summary:
      'Una tradición ascética centrada en la no violencia absoluta (ahimsa). Cada alma (jiva) es eterna y se libera depurándose del karma.',
    ideas: [
      'Ahimsa hacia todos los seres vivos, con una ética alimentaria y de conducta muy estricta.',
      'Anekantavada: la verdad tiene muchas caras; ninguna perspectiva la agota.',
      'Los cinco votos: no violencia, verdad, no robar, castidad y no apego.',
    ],
    yogaLink: 'Los cinco votos jainas son casi idénticos a los yamas de Patanjali, y de ahí viene el ahimsa del yoga.',
    link: { href: '/yoga/ocho_ramas_del_yoga', label: 'Ver los yamas en las 8 ramas →' },
    color: 'teal',
  },
  {
    id: 'budismo',
    group: 'nastika',
    name: 'Budismo',
    note: 'El Camino medio',
    icon: '☸️',
    founder: 'Siddhartha Gautama (el Buda)',
    text: 'Tripitaka (Canon Pali)',
    era: 'c. siglo V a.C.',
    summary:
      'Nace de la experiencia del Buda al buscar el fin del sufrimiento entre el exceso y la mortificación: el Camino medio.',
    ideas: [
      'Cuatro Nobles Verdades: el sufrimiento, su origen, su cese y el camino hacia él.',
      'Óctuple sendero: visión, intención, palabra, acción, medio de vida, esfuerzo, atención y concentración correctos.',
      'Anatta: no hay un yo fijo; tampoco un Atman permanente.',
    ],
    yogaLink: 'Comparte con el yoga la meditación, la ética y la atención plena (smriti / sati); influencia y se deja influir durante siglos.',
    color: 'fuchsia',
  },
];

export const GROUPS = {
  astika: { label: 'Ástika', count: 6, desc: 'Aceptan la autoridad de los Vedas' },
  nastika: { label: 'Nástika', count: 3, desc: 'No aceptan la autoridad de los Vedas' },
};
