import { ashtangaSequence } from '../yoga/ashtanga_serie_basica_1/ashtangaSequence';

// Catálogo completo de asanas — usa como base la Primera Serie de Ashtanga
// ya definida en el sitio (mismas fotografías, crédito original a Keen on
// Yoga: https://www.keenonyoga.com/ashtanga-yoga-primary-series/).
//
// Contenido ampliado investigado en Yoga Journal, Yoga Basics, MyYogaTeacher,
// Samyak Yoga, Ashtanga Yoga Boston y Wikipedia: historia del método de
// Krishnamacharya y Pattabhi Jois, mitología asociada a cada asana cuando
// existe, y la lectura energética tradicional (chakras, nadis, vayus) propia
// del hatha yoga clásico — presentada como enseñanza tradicional, no como
// hecho científico.

const nameOrigins = {
  Samasthiti: { tag: '🌿 Naturaleza' },
  'Utthita Trikonasana': { tag: '📐 Geometría' },
  'Parivrtta Trikonasana': { tag: '📐 Geometría' },
  Utkatasana: { tag: '📐 Geometría' },
  Navasana: { tag: '📐 Geometría' },
  Kurmasana: { tag: '🐾 Animal' },
  'Supta Kurmasana': { tag: '🐾 Animal' },
  'Baddha Konasana': { tag: '🐾 Animal' },
  'Urdhva Dhanurasana': { tag: '📐 Geometría' },
  Halasana: { tag: '🌿 Naturaleza' },
  Matsyasana: { tag: '🐾 Animal' },
  'Virabhadrasana A & B': { tag: '📜 Mitología' },
  'Marichyasana A, B, C, D': { tag: '📜 Mitología' },
};

const details = {
  Samasthiti: {
    entrada: 'Ponte de pie al frente del mat, con los pies juntos o al ancho de la cadera. Reparte el peso en las cuatro esquinas de ambos pies.',
    mantenimiento: 'Activa los cuádriceps, alarga la columna desde el coxis hasta la coronilla, abre el pecho y relaja los hombros lejos de las orejas. Respira 5 ciclos completos.',
    salida: 'Con una inhalación, prepárate para el primer saludo al sol elevando los brazos por los costados.',
    mistakes: ['Bloquear las rodillas hacia atrás en vez de activarlas suavemente.', 'Dejar caer el peso hacia los talones o las puntas en lugar de repartirlo parejo.'],
    visualization: 'Imagina raíces creciendo desde tus pies hacia el centro de la tierra mientras la coronilla se eleva como la cima de una montaña hacia el cielo.',
    history: 'Samasthiti abre cada serie de Ashtanga Vinyasa tal como la sistematizó Pattabhi Jois en Mysore: es el punto neutro desde el que se cuentan todas las vinyasas de la práctica.',
    energetics: 'Se la considera el punto de reseteo energético entre posturas: estabiliza mula bandha y devuelve la atención a la respiración antes de avanzar.',
  },
  Padangusthasana: {
    entrada: 'Desde Samasthiti, separa los pies al ancho de la cadera. Inhala para alargar la columna con las manos en las caderas.',
    mantenimiento: 'Exhala y pliega el torso hacia adelante desde las caderas, sujeta los dedos gordos con índice, medio y pulgar. Alarga en cada inhalación, profundiza en cada exhalación.',
    salida: 'Inhala para levantar la cabeza y alargar la espalda a media altura antes de soltar las manos y continuar hacia Padahastasana.',
    mistakes: ['Redondear la espalda alta para "llegar" más abajo en vez de plegarse desde la cadera.', 'Bloquear las rodillas con fuerza excesiva; mejor mantener una microflexión si los isquiotibiales están tensos.'],
    visualization: 'Visualiza la columna como un puente colgante que se despliega hacia el suelo, cable por cable, sin colapsar en el centro.',
    history: 'Es la primera flexión de pie de la secuencia y prepara el patrón articular que se repite en Padahastasana; ambas se enseñan siempre como pareja inseparable.',
    energetics: 'Las flexiones hacia adelante se asocian tradicionalmente con apana vayu, la energía descendente vinculada a la liberación y el desapego.',
  },
  Padahastasana: {
    entrada: 'Desde Padangusthasana, desliza las palmas debajo de las plantas de los pies, con los dedos hacia los talones.',
    mantenimiento: 'Exhala y profundiza la flexión presionando los pies contra las manos; mantén las piernas activas y la coronilla apuntando al suelo.',
    salida: 'Inhala y libera las manos, alarga la espalda a media altura antes de exhalar y regresar a Samasthiti.',
    mistakes: ['Forzar la profundidad tirando del cuello en vez de plegarse desde la cadera.', 'Dejar que los pies pierdan el contacto activo con el suelo.'],
    visualization: 'Siente cómo cada exhalación te ancla un poco más al suelo, como si el peso de la cabeza disolviera la tensión de la espalda baja.',
    history: 'Comparte raíz con Padangusthasana; juntas forman la introducción clásica a las posturas de pie de la Primera Serie.',
    energetics: 'Profundiza el efecto calmante de apana vayu y prepara el sistema nervioso para el ritmo más activo de las posturas de pie que siguen.',
  },
  'Utthita Trikonasana': {
    entrada: 'Separa los pies un metro aproximadamente. Gira el pie derecho 90° y el izquierdo ligeramente hacia adentro; extiende los brazos en cruz.',
    mantenimiento: 'Exhala e inclina el torso hacia el pie derecho desde la cadera. Apoya la mano derecha en la espinilla o el suelo y extiende la izquierda hacia el techo, mirando hacia arriba.',
    salida: 'Inhala, presiona ambos pies contra el suelo y usa el core para regresar el torso a vertical antes de repetir del otro lado.',
    mistakes: ['Doblar la rodilla delantera en vez de mantenerla extendida y activa.', 'Colapsar el pecho hacia el suelo en lugar de abrirlo hacia el lateral.'],
    visualization: 'Imagina tu cuerpo como un triángulo perfecto tallado en el espacio: tres líneas rectas —piernas, torso y brazo— sosteniéndose entre sí sin esfuerzo.',
    history: 'Trikona significa "tres ángulos"; es una de las pocas asanas de la Primera Serie cuyo nombre remite a la geometría pura y no a un ser vivo o un sabio.',
    energetics: 'La apertura lateral del costado se vincula con la liberación de manipura chakra, el centro energético asociado a la voluntad y la claridad mental.',
  },
  'Parivrtta Trikonasana': {
    entrada: 'Desde una base similar al triángulo pero con los pies más cerca entre sí, cuadra las caderas hacia el frente.',
    mantenimiento: 'Exhala y gira el torso, llevando la mano opuesta al exterior del pie delantero o al suelo; el otro brazo se eleva mientras la mirada sigue la mano.',
    salida: 'Inhala para deshacer la torsión y regresar el torso a vertical antes de exhalar y repetir del otro lado.',
    mistakes: ['Girar desde la zona lumbar en vez de rotar desde el abdomen y la caja torácica.', 'Perder el cuadre de las caderas dejando que la cadera trasera se abra hacia atrás.'],
    visualization: 'Imagina la columna como el eje de una brújula: el giro nace del centro y se irradia hacia manos y mirada sin perder el equilibrio de la aguja.',
    history: 'Es la contraparte en torsión de Utthita Trikonasana; ambas comparten la raíz "trikona" y suelen enseñarse como par para equilibrar apertura lateral y rotación.',
    energetics: 'Las torsiones se describen tradicionalmente como un "escurrido" de los órganos internos que estimula agni, el fuego digestivo, y libera tensión acumulada.',
  },
  'Utthita Parsvakonasana': {
    entrada: 'Desde la base amplia del triángulo, dobla la rodilla delantera a 90 grados manteniendo el talón alineado bajo la rodilla.',
    mantenimiento: 'Exhala y lleva la mano al suelo por fuera del pie delantero, extendiendo el brazo superior en una línea diagonal continua desde el talón trasero hasta la punta de los dedos.',
    salida: 'Inhala, presiona el talón trasero y endereza la pierna delantera para regresar a la base amplia antes de repetir del otro lado.',
    mistakes: ['Dejar caer la rodilla delantera hacia adentro en vez de alinearla con el segundo dedo del pie.', 'Cortar la línea diagonal del cuerpo doblando la muñeca o el codo del brazo superior.'],
    visualization: 'Visualiza una línea de energía continua que atraviesa todo tu cuerpo en diagonal, del talón trasero a la punta de los dedos, como un rayo de luz sin quiebres.',
    history: 'Forma parte del bloque de posturas de pie que, según relatan alumnos directos de Pattabhi Jois, ya se practicaban en las clases matutinas de Mysore en los años 30.',
    energetics: 'La extensión lateral profunda abre los canales energéticos (nadis) a lo largo del costado del cuerpo, favoreciendo la circulación de prana hacia las extremidades.',
  },
  'Parivrtta Parsvakonasana': {
    entrada: 'Desde una estocada profunda con la rodilla delantera en 90 grados, lleva las palmas a juntarse frente al pecho.',
    mantenimiento: 'Exhala, gira el torso y engancha el codo opuesto por fuera de la rodilla delantera, presionando las palmas para profundizar la torsión mientras el talón trasero busca el suelo.',
    salida: 'Inhala para deshacer la torsión, regresa a la estocada neutra y exhala antes de repetir del otro lado.',
    mistakes: ['Levantar el talón trasero del suelo para "ganar" torsión en vez de mantenerlo anclado.', 'Empujar el codo contra la rodilla con fuerza en vez de profundizar gradualmente con la respiración.'],
    visualization: 'Imagina que exprimes una toalla mojada desde el centro del abdomen hacia afuera, soltando con cada exhalación lo que ya no necesitas sostener.',
    history: 'Se la considera una de las posturas de pie más exigentes de la Primera Serie por combinar estocada profunda, torsión y equilibrio en una sola forma.',
    energetics: 'Como torsión profunda, se asocia con la purificación de los nadis y el estímulo del fuego digestivo (agni) en la zona del plexo solar.',
  },
  'Prasarita Padottanasana A, B, C, D': {
    entrada: 'Separa los pies un metro y medio aproximadamente, con los bordes externos paralelos. En A, las manos van al suelo entre los pies.',
    mantenimiento: 'Exhala y profundiza la flexión en cada variante: B con las manos en las caderas y el torso plano, C con los dedos entrelazados detrás de la espalda, D sujetando los dedos gordos.',
    salida: 'Inhala para alargar la espalda entre cada variante; al finalizar D, presiona los pies y regresa a vertical con los brazos elevados.',
    mistakes: ['Cargar todo el peso en las puntas de los pies en lugar de repartirlo en toda la planta.', 'Forzar la coronilla al suelo en la variante A sacrificando la extensión de la columna.'],
    visualization: 'Siente las cuatro variantes como capas de una misma respiración: cada exhalación te lleva un poco más profundo, sin prisa, como agua que encuentra su nivel.',
    history: 'Las cuatro variantes (A-D) se enseñan como una secuencia continua; esta estructura de "letras" es característica del método con el que Pattabhi Jois transmitía variaciones de una misma base.',
    energetics: 'La inversión parcial de la cabeza favorece un efecto calmante sobre el sistema nervioso, similar al de las inversiones completas pero más accesible.',
  },
  Parsvottanasana: {
    entrada: 'Con los pies en una postura corta, cuadra las caderas hacia el frente y junta las palmas en saludo invertido detrás de la espalda si es posible.',
    mantenimiento: 'Exhala y dóblate sobre la pierna delantera manteniendo la espalda larga, sin redondear, hasta donde la flexibilidad de isquiotibiales lo permita.',
    salida: 'Inhala para levantar el torso a vertical, manteniendo las caderas cuadradas, antes de girar y repetir del otro lado.',
    mistakes: ['Rotar la cadera trasera hacia afuera para "cuadrar" en exceso, perdiendo la alineación de la pelvis.', 'Forzar el saludo invertido a costa de encorvar los hombros hacia adelante.'],
    visualization: 'Imagina dos faros en tus caderas apuntando siempre hacia el mismo punto al frente, como guías que no se apagan mientras el torso se inclina.',
    history: 'También llamada "postura de la pirámide" por la forma triangular que dibuja el cuerpo de perfil; es un puente clásico entre las posturas de pie amplias y las de equilibrio.',
    energetics: 'El saludo invertido detrás de la espalda se enseña como un gesto de humildad que abre el corazón mientras el resto del cuerpo se repliega.',
  },
  'Utthita Hasta Padangusthasana': {
    entrada: 'De pie en Samasthiti, lleva el peso a una pierna, flexiona la otra rodilla hacia el pecho y sujeta el dedo gordo con dos dedos.',
    mantenimiento: 'Extiende la pierna elevada hacia adelante manteniendo la espalda recta; luego ábrela hacia el lateral sin girar la cadera de apoyo, y finalmente pliega la cabeza hacia la rodilla.',
    salida: 'Suelta el dedo gordo, lleva la rodilla de nuevo al pecho y baja el pie con control antes de repetir del otro lado.',
    mistakes: ['Inclinar todo el torso hacia atrás para compensar la altura de la pierna en vez de mantenerla moderada y controlada.', 'Dejar que la cadera de la pierna elevada rote hacia afuera al abrirla al lateral.'],
    visualization: 'Imagina un hilo invisible que conecta la coronilla con el cielo mientras la pierna se extiende como la aguja de un compás trazando un arco preciso.',
    history: 'Es la primera postura de equilibrio sobre una pierna de la secuencia; su nombre describe literalmente la acción física, sin referencia mitológica.',
    energetics: 'El equilibrio sostenido en un solo pie se enseña tradicionalmente como entrenamiento de ekagrata, la concentración en un punto único.',
  },
  'Ardha Baddha Padmottanasana': {
    entrada: 'De pie, coloca un pie en medio loto sobre el muslo opuesto y rodea la espalda con el brazo del mismo lado para sujetar el pie.',
    mantenimiento: 'Exhala y dóblate hacia adelante sobre la pierna de apoyo, manteniendo la espalda larga y la cadera del pie en loto nivelada.',
    salida: 'Inhala para levantar el torso, suelta el pie con cuidado y desarma el medio loto antes de repetir del otro lado.',
    mistakes: ['Forzar la rodilla del pie en loto hacia el suelo en vez de dejar que la cadera se abra a su propio ritmo.', 'Cargar todo el peso en la pierna de apoyo sin activar el pie en loto para sostener el equilibrio.'],
    visualization: 'Visualiza la rodilla flexionada como una flor de loto que se abre lentamente, sin forzar sus pétalos antes de tiempo.',
    history: 'Combina el medio loto —símbolo clásico de la meditación— con una flexión de pie, anticipando el trabajo de cadera en loto completo de Baddha Padmasana.',
    energetics: 'El loto, aunque sea parcial, se asocia en la tradición con la apertura de las caderas como sede de emociones retenidas.',
  },
  Utkatasana: {
    entrada: 'Desde Samasthiti, inhala y dobla las rodillas como si te sentaras en una silla invisible, elevando los brazos con las palmas juntas.',
    mantenimiento: 'Mantén el peso en los talones, el coxis ligeramente metido y la mirada hacia los pulgares; respira 5 ciclos manteniendo la activación de los muslos.',
    salida: 'Exhala, endereza las piernas y baja los brazos, regresando a Samasthiti.',
    mistakes: ['Dejar que las rodillas se adelanten mucho más allá de la punta de los pies.', 'Elevar los hombros hacia las orejas en vez de mantenerlos relajados lejos del cuello.'],
    visualization: 'Imagina que te sientas sobre una silla de fuego interno: incómoda pero estable, sostenida por la fuerza de tus propias piernas.',
    history: 'Utkata significa "poderosa" o "feroz", no "silla"; el apodo popular surgió de la forma que dibujan las piernas, aunque el nombre sánscrito describe la intensidad del esfuerzo.',
    energetics: 'El esfuerzo sostenido en las piernas se asocia con el fortalecimiento de la voluntad (manipura chakra) y la generación de calor interno (tapas).',
  },
  'Virabhadrasana A & B': {
    entrada: 'Desde una estocada profunda con el talón trasero anclado a 45°, en A cuadra las caderas al frente; en B, ábrelas hacia el lateral.',
    mantenimiento: 'En A, eleva los brazos con las palmas juntas y mira hacia arriba; en B, abre los brazos paralelos al suelo y mira por encima de la mano delantera.',
    salida: 'Endereza la pierna delantera, gira los pies y repite la secuencia hacia el otro lado antes de regresar a Samasthiti.',
    mistakes: ['Dejar que la rodilla delantera colapse hacia adentro en vez de alinearla con el segundo dedo del pie.', 'Inclinar el torso hacia adelante en A en vez de mantenerlo vertical sobre la pelvis.'],
    visualization: 'Siente en tu pecho la determinación de un guerrero que se levanta después de la batalla: firme, presente, sin agresión, solo fuerza tranquila.',
    history: 'Virabhadra nació de un mechón de cabello de Shiva, enfurecido por la muerte de su esposa Sati; las posturas del guerrero recrean los momentos en que Virabhadra emerge, empuña la espada y se prepara para actuar.',
    energetics: 'Se enseña como una postura de activación de manipura chakra: canaliza la fuerza y la determinación sin perder el centro.',
  },
  Dandasana: {
    entrada: 'Siéntate con las piernas extendidas al frente, apoyando las manos junto a las caderas.',
    mantenimiento: 'Activa los pies flexionando los tobillos y presiona las manos contra el suelo para alargar la columna a 90 grados exactos respecto a las piernas.',
    salida: 'Mantén esta alineación como base de referencia antes de plegarte hacia adelante en Paschimottanasana.',
    mistakes: ['Redondear la espalda baja en vez de mantenerla en extensión neutra.', 'Dejar que los pies caigan pasivamente en lugar de mantenerlos activos y flexionados.'],
    visualization: 'Imagina tu columna como el mástil de un barco y tus piernas como la línea de flotación: ambos en ángulo recto, estables y alineados.',
    history: 'Dandasana ("postura del bastón") es la referencia de todas las flexiones sentadas de la Primera Serie: su alineación se repite como base en Paschimottanasana, Janu Sirsasana y Marichyasana.',
    energetics: 'Se considera la "Tadasana sentada": el punto neutro desde el que se organiza la energía antes de cualquier flexión o torsión en el suelo.',
  },
  Paschimottanasana: {
    entrada: 'Desde Dandasana, inhala para alargar la columna con los brazos elevados.',
    mantenimiento: 'Exhala y pliega el torso hacia adelante desde la cadera, sujetando los pies o las espinillas; alarga en cada inhalación, profundiza en cada exhalación.',
    salida: 'Inhala para levantar la cabeza y el pecho, alargando la espalda a media altura antes de soltar y regresar a Dandasana.',
    mistakes: ['Tirar del torso con los brazos para "llegar más lejos" en vez de plegarse desde la articulación de la cadera.', 'Dejar que los pies caigan hacia afuera en lugar de mantenerlos activos y paralelos.'],
    visualization: 'Imagina que tu torso se derrama lentamente sobre las piernas como agua que fluye cuesta abajo, sin resistencia ni prisa.',
    history: 'Paschima significa "oeste" y se refiere simbólicamente a la parte posterior del cuerpo; es una de las flexiones hacia adelante mencionadas ya en el Hatha Yoga Pradipika.',
    energetics: 'Las flexiones profundas hacia adelante se vinculan con apana vayu y con un efecto introspectivo que calma la mente y el sistema nervioso.',
  },
  Purvottanasana: {
    entrada: 'Desde Dandasana, coloca las manos detrás de ti con los dedos apuntando hacia los pies.',
    mantenimiento: 'Al inhalar, presiona las manos y los pies para elevar las caderas formando una línea recta desde los talones hasta la cabeza, que puede caer hacia atrás si el cuello lo permite.',
    salida: 'Exhala y baja las caderas con control de vuelta a Dandasana.',
    mistakes: ['Dejar que las caderas caigan por debajo de la línea del cuerpo en vez de elevarlas a la altura de los hombros.', 'Forzar la cabeza hacia atrás generando tensión en el cuello.'],
    visualization: 'Imagina tu cuerpo como una tabla de madera perfectamente recta, tensada de punta a punta sin que ningún punto ceda.',
    history: 'Purva significa "este", el lado opuesto a paschima; es la contrapostura natural de Paschimottanasana dentro del par que abre y cierra el frente del cuerpo.',
    energetics: 'Al abrir el frente del cuerpo, se asocia con la activación de anahata chakra, el centro energético del corazón.',
  },
  'Janu Sirsasana A, B, C': {
    entrada: 'Desde Dandasana, dobla una rodilla llevando el talón hacia el perineo (A), sentándote sobre el talón (B), o con los dedos del pie doblados bajo el muslo (C).',
    mantenimiento: 'Exhala y pliega el torso sobre la pierna extendida, sujetando el pie con ambas manos; alarga en cada inhalación, profundiza en cada exhalación.',
    salida: 'Inhala para levantar el torso y desarmar la posición de la pierna doblada antes de repetir del otro lado.',
    mistakes: ['Dejar que la cadera de la pierna extendida se eleve del suelo en vez de mantenerla anclada.', 'Girar el torso hacia la pierna doblada en lugar de mantenerlo cuadrado sobre la pierna extendida.'],
    visualization: 'Imagina que inclinas la cabeza hacia la rodilla como una flor que se inclina hacia el sol, guiada por la respiración y no por la fuerza.',
    history: 'Janu Sirsasana ("cabeza a la rodilla") es una de las flexiones asimétricas más antiguas del hatha yoga; sus tres variantes fueron incorporadas por Krishnamacharya para intensificar progresivamente el estiramiento de cadera.',
    energetics: 'La asimetría de la postura permite trabajar cada lado del cuerpo por separado, equilibrando el flujo de prana entre ida y pingala nadi.',
  },
  'Marichyasana A, B, C, D': {
    entrada: 'Desde Dandasana, dobla una rodilla llevando el talón cerca del glúteo; en C y D, gira el torso hacia la pierna doblada.',
    mantenimiento: 'En A y B, envuelve el brazo alrededor de la pierna doblada y ata las manos detrás de la espalda mientras te pliegas hacia adelante; en C y D, usa el mismo enganche para profundizar la torsión.',
    salida: 'Deshaz la atadura con cuidado, endereza la pierna y regresa a Dandasana antes de repetir del otro lado.',
    mistakes: ['Forzar la atadura de las manos tirando desde el hombro en vez de rotarlo desde la escápula.', 'Perder la extensión de la columna al enfocarse solo en cerrar el enganche de las manos.'],
    visualization: 'Imagina un rayo de luz —como el propio nombre "Marichi" sugiere— que atraviesa tu columna y guía la torsión desde el centro hacia afuera.',
    history: 'Está dedicada al sabio Marichi, hijo de Brahma y uno de los siete Manasaputras (hijos nacidos de la mente del creador) en la mitología védica.',
    energetics: 'Las ataduras y torsiones se enseñan como un "exprimido" energético que estimula agni y libera tensión emocional retenida en la zona lumbar.',
  },
  Navasana: {
    entrada: 'Desde Dandasana, inclina el torso ligeramente hacia atrás y eleva las piernas, apoyándote sobre los isquiones.',
    mantenimiento: 'Extiende los brazos paralelos al suelo y las piernas activas, formando una V con el torso; mantén 5 respiraciones y repite la elevación 5 veces.',
    salida: 'Baja las piernas y las manos con control, cruza los tobillos y continúa hacia Bhujapidasana.',
    mistakes: ['Redondear la espalda baja para sostener el equilibrio en vez de mantener el pecho abierto.', 'Dejar caer los hombros hacia adelante en lugar de mantenerlos alineados sobre la pelvis.'],
    visualization: 'Imagina tu cuerpo como un bote pequeño balanceándose sobre el agua en calma, estable gracias a un centro de gravedad firme, no a la tensión de los brazos.',
    history: 'Nava significa "bote"; la postura recrea la forma de una embarcación equilibrándose sobre el agua y se repite cinco veces como ejercicio de fortalecimiento del core.',
    energetics: 'El trabajo intenso del abdomen se vincula con manipura chakra, el centro del fuego interno y la voluntad personal.',
  },
  Bhujapidasana: {
    entrada: 'En cuclillas, coloca las manos en el suelo al ancho de los hombros y desliza los muslos por encima de los brazos, cerca de los hombros.',
    mantenimiento: 'Inclínate hacia adelante, cruza los tobillos frente a los brazos y eleva los pies del suelo, sosteniendo el peso sobre las manos.',
    salida: 'Baja la frente hacia el suelo si es posible, luego eleva la cabeza y regresa los pies al suelo con control antes de continuar hacia Kurmasana.',
    mistakes: ['Apoyar el peso en las muñecas en extensión completa en vez de repartirlo en toda la palma.', 'Encoger los hombros hacia las orejas en lugar de mantenerlos activos y alejados del cuello.'],
    visualization: 'Imagina que tus brazos son dos estantes firmes que sostienen sin esfuerzo el peso de todo tu cuerpo, como ramas que sostienen fruta madura.',
    history: 'Es una de las primeras posturas de equilibrio sobre brazos de la Primera Serie y sirve de preparación física directa para Kurmasana y Supta Kurmasana.',
    energetics: 'El equilibrio sobre las manos se asocia con el fortalecimiento del fuego digestivo y la estabilidad del plexo solar.',
  },
  Kurmasana: {
    entrada: 'Sentado con las piernas separadas y las rodillas dobladas, desliza los brazos por debajo de las rodillas hacia los lados.',
    mantenimiento: 'Exhala y baja el torso y la barbilla hacia el suelo, extendiendo gradualmente las piernas mientras los brazos se deslizan hacia atrás bajo las rodillas.',
    salida: 'Inhala para levantar el torso y recoger los brazos, doblando las piernas antes de transicionar hacia Supta Kurmasana.',
    mistakes: ['Forzar la extensión de las piernas antes de que los hombros hayan encontrado espacio bajo las rodillas.', 'Levantar la cabeza en vez de dejar que la barbilla se relaje hacia el suelo.'],
    visualization: 'Imagina que te repliegas hacia tu propio caparazón, como una tortuga que se retira del mundo exterior para descansar en su centro más profundo.',
    history: 'Kurma es la tortuga, el segundo avatar de Vishnú, que sostuvo el Monte Mandara sobre su caparazón durante el batido del océano de leche (Samudra Manthan).',
    energetics: 'El repliegue hacia adentro se describe tradicionalmente como pratyahara físico: el retiro de los sentidos hacia el interior, un paso previo a la meditación profunda.',
  },
  'Supta Kurmasana': {
    entrada: 'Desde Kurmasana, cruza los tobillos detrás de la cabeza.',
    mantenimiento: 'Ata las manos detrás de la espalda baja, entrelazando los dedos mientras el torso permanece plegado y relajado bajo las piernas.',
    salida: 'Desata las manos, descruza los tobillos con cuidado y regresa a una posición sentada.',
    mistakes: ['Forzar el cruce de tobillos sin la apertura de cadera suficiente, generando tensión en las rodillas.', 'Contener la respiración por la intensidad de la postura en vez de mantener un ritmo constante.'],
    visualization: 'Imagina que te disuelves completamente en el suelo, como una tortuga profundamente dormida, sin ninguna parte del cuerpo en tensión.',
    history: 'Es la variante "dormida" de Kurmasana y una de las posturas más avanzadas de la Primera Serie, documentada en los tratados de hatha yoga del siglo XX asociados a Krishnamacharya.',
    energetics: 'Representa el punto más profundo de repliegue interior de la serie, asociado con la quietud total de la mente antes de las posturas de equilibrio invertido.',
  },
  'Baddha Konasana': {
    entrada: 'Sentado, dobla las rodillas y junta las plantas de los pies, acercando los talones al perineo.',
    mantenimiento: 'En la versión A, mantén la espalda recta sujetando los pies; en la B, pliega el torso hacia adelante manteniendo las rodillas cerca del suelo.',
    salida: 'Inhala para levantar el torso, suelta los pies y extiende las piernas antes de continuar hacia Upavishta Konasana.',
    mistakes: ['Presionar las rodillas hacia el suelo con las manos en vez de dejar que la apertura llegue de forma natural.', 'Redondear la espalda en la versión A en lugar de mantenerla extendida.'],
    visualization: 'Imagina las piernas como las alas de una mariposa que se abren y cierran suavemente al ritmo de tu respiración.',
    history: 'Su nombre sánscrito significa "ángulo atado" y también se la conoce como "postura del zapatero" por la posición de trabajo tradicional en India; en Occidente se la apoda "postura de la mariposa".',
    energetics: 'La apertura de cadera se asocia tradicionalmente con la liberación emocional almacenada en esa zona del cuerpo, vinculada a svadhisthana chakra.',
  },
  'Upavishta Konasana': {
    entrada: 'Sentado, separa las piernas lo más ancho que sea cómodo, activando los pies hacia arriba.',
    mantenimiento: 'Exhala y pliega el torso hacia adelante manteniendo la espalda extendida, sujetando los pies o los tobillos.',
    salida: 'Inhala para levantar el torso y junta las piernas con las manos si es necesario antes de continuar la secuencia.',
    mistakes: ['Redondear la espalda para ganar profundidad en vez de plegarse desde la cadera.', 'Dejar que las rodillas y los pies caigan hacia adentro en lugar de mantenerlos activos hacia el techo.'],
    visualization: 'Imagina un compás abierto en el suelo, con la columna como la aguja central que se inclina hacia adelante sin perder su eje.',
    history: 'Es la flexión de ángulo abierto más amplia de la Primera Serie y cierra el bloque de posturas sentadas de cadera antes de las flexiones hacia atrás.',
    energetics: 'Al igual que Baddha Konasana, se asocia con la apertura de svadhisthana chakra y la liberación de tensión en la parte interna de los muslos.',
  },
  'Urdhva Dhanurasana': {
    entrada: 'Acostado boca arriba, dobla las rodillas y coloca los pies cerca de los glúteos; las manos junto a las orejas con los dedos apuntando a los hombros.',
    mantenimiento: 'Al inhalar, presiona manos y pies para elevar caderas y pecho, dejando que la cabeza cuelgue relajada mientras los brazos se enderezan.',
    salida: 'Exhala y baja la columna con control, vértebra por vértebra, hasta apoyar la espalda completa en el suelo.',
    mistakes: ['Cargar el peso solo en las muñecas sin activar las piernas para compartir el esfuerzo.', 'Dejar que los codos se abran hacia afuera en lugar de mantenerlos alineados con los hombros.'],
    visualization: 'Imagina tu cuerpo como un arco tensado, listo para liberar una flecha de energía desde el centro del pecho hacia el cielo.',
    history: 'Dhanu significa "arco"; en Occidente también se la conoce como "rueda" por la forma circular que dibuja la columna en su máxima expresión.',
    energetics: 'Las flexiones profundas hacia atrás se asocian con la activación de anahata chakra y una liberación intensa de energía acumulada en el pecho y los hombros.',
  },
  'Salamba Sarvangasana': {
    entrada: 'Desde Savasana o rodando desde Halasana, eleva las piernas y la espalda apoyando el peso en los hombros y la parte superior de los brazos.',
    mantenimiento: 'Sostén la espalda baja con las manos, mantén el cuerpo en una línea vertical desde los hombros hasta los pies, con la barbilla ligeramente hacia el pecho.',
    salida: 'Baja la columna con control vértebra por vértebra hasta apoyar la espalda completa, o transiciona directamente hacia Halasana.',
    mistakes: ['Girar la cabeza mientras se sostiene el peso sobre los hombros, lo cual pone en riesgo el cuello.', 'Dejar que los codos se abran demasiado en vez de mantenerlos cerca del cuerpo para sostener la espalda.'],
    visualization: 'Imagina que tu cuerpo es una vela encendida, perfectamente vertical y quieta, con la llama en la punta de los pies.',
    history: 'Sarvanga significa "todo el cuerpo": se la considera una de las posturas más completas del hatha yoga clásico por su efecto integral sobre la circulación y el sistema nervioso.',
    energetics: 'Las inversiones se asocian tradicionalmente con la estimulación de vishuddha chakra, en la garganta, y con un efecto profundamente calmante sobre el sistema nervioso.',
  },
  Halasana: {
    entrada: 'Desde Salamba Sarvangasana, baja las piernas lentamente por detrás de la cabeza, manteniéndolas activas.',
    mantenimiento: 'Apoya los dedos de los pies en el suelo, entrelaza las manos detrás de la espalda o apóyalas en la espalda baja para sostener la extensión de la columna.',
    salida: 'Con las manos como apoyo, rueda la columna de vuelta hacia Sarvangasana o baja con control hasta el suelo.',
    mistakes: ['Forzar los pies hacia el suelo si la espalda o los isquiotibiales no lo permiten, generando tensión cervical.', 'Dejar que el peso colapse hacia el cuello en lugar de sostenerlo con los brazos.'],
    visualization: 'Imagina que tu columna traza el mismo surco profundo que deja un arado al remover la tierra, abriendo camino para una nueva siembra.',
    history: 'Hala significa "arado", la herramienta agrícola tradicional; su forma recuerda el movimiento de labrar la tierra, un símbolo de renovación en la cultura védica.',
    energetics: 'Como inversión profunda, intensifica el efecto calmante de Sarvangasana y se asocia con la introspección y el silencio mental.',
  },
  Karnapidasana: {
    entrada: 'Desde Halasana, dobla las rodillas y llévalas hacia el suelo a los lados de las orejas.',
    mantenimiento: 'Mantén los brazos extendidos en el suelo o abrazando las piernas, con las orejas suavemente cubiertas por las rodillas.',
    salida: 'Extiende las piernas de vuelta a Halasana o rueda con control hacia Sarvangasana antes de bajar.',
    mistakes: ['Forzar las rodillas al suelo generando tensión excesiva en el cuello y la zona cervical.', 'Contener la respiración por la presión en las orejas en vez de mantenerla fluida.'],
    visualization: 'Imagina que el mundo exterior se silencia por completo, como si las rodillas cerraran una puerta suave hacia el ruido externo.',
    history: 'Karna significa "oído" y pida, "presión": el nombre describe literalmente la acción de la postura, una variante de cierre de Halasana.',
    energetics: 'Se enseña como el punto de mayor introspección sensorial de la secuencia, un pratyahara físico que antecede a las posturas de cierre.',
  },
  Matsyasana: {
    entrada: 'Acostado boca arriba con las piernas extendidas o en loto, apoya los antebrazos en el suelo junto al cuerpo.',
    mantenimiento: 'Arquea la espalda alta, apoya la coronilla en el suelo (sin cargar peso sobre ella) y abre el pecho hacia el techo.',
    salida: 'Presiona los antebrazos para levantar la cabeza y bajar la columna con control hasta apoyarla completamente en el suelo.',
    mistakes: ['Cargar el peso de la cabeza sobre la coronilla en vez de sostenerlo con los antebrazos.', 'Forzar la apertura del pecho sin activar las piernas, perdiendo estabilidad en la postura.'],
    visualization: 'Imagina tu pecho como las agallas de un pez que se abren para respirar libremente, mientras la columna se curva con la misma gracia con la que un pez nada contra la corriente.',
    history: 'Matsya es el pez, el primer avatar de Vishnú, que según la mitología salvó a la humanidad de un diluvio universal guiando el arca de Manu.',
    energetics: 'Es la contrapostura clásica de las inversiones: reabre la garganta y el pecho después del repliegue de Sarvangasana, Halasana y Karnapidasana.',
  },
  Sirsasana: {
    entrada: 'Entrelaza los dedos en el suelo formando un trípode con los antebrazos, apoya la coronilla en el hueco de las manos.',
    mantenimiento: 'Eleva las caderas, camina los pies hacia el cuerpo y despega las piernas del suelo, activando el core para mantener una línea vertical estable.',
    salida: 'Baja las piernas con el mismo control con el que subieron y descansa en Balasana antes de continuar.',
    mistakes: ['Cargar el peso sobre la cabeza en vez de distribuirlo entre los antebrazos y los hombros.', 'Usar el impulso de las piernas para subir en lugar de elevarlas con control desde el core.'],
    visualization: 'Imagina que el mundo se invierte suavemente mientras tú permaneces perfectamente quieto, como el eje inmóvil alrededor del cual todo lo demás gira.',
    history: 'Sirsasana es conocida como "la reina de las asanas" en la tradición del hatha yoga clásico, por su efecto integral sobre la circulación y el sistema nervioso central.',
    energetics: 'Se asocia con la activación de sahasrara y ajna chakra, en la coronilla y el entrecejo, vinculados a la claridad mental y la intuición.',
  },
  'Baddha Padmasana': {
    entrada: 'Siéntate en Padmasana completo, con ambos pies apoyados sobre los muslos opuestos.',
    mantenimiento: 'Cruza los brazos por detrás de la espalda y sujeta los dedos gordos de los pies opuestos, manteniendo la columna erguida.',
    salida: 'Suelta la atadura de las manos y desarma el loto con cuidado, liberando primero una pierna y luego la otra.',
    mistakes: ['Forzar la atadura de las manos sacrificando la extensión de la columna.', 'Desarmar el loto de forma brusca en vez de liberar las rodillas gradualmente.'],
    visualization: 'Imagina tu cuerpo cerrándose en un círculo completo de energía, sin principio ni fin, como una flor de loto perfectamente sellada sobre sí misma.',
    history: 'El loto atado combina dos símbolos centrales del hatha yoga clásico —el loto y la atadura— y suele reservarse para practicantes con suficiente apertura de cadera y hombros.',
    energetics: 'Se considera una de las posturas de sello energético (bandha) más completas: contiene y concentra la energía acumulada durante toda la práctica.',
  },
  Utpluthih: {
    entrada: 'Desde Baddha Padmasana o Padmasana, coloca las palmas en el suelo junto a las caderas.',
    mantenimiento: 'Presiona las manos contra el suelo y levanta todo el cuerpo, piernas cruzadas incluidas, manteniendo la elevación entre 10 y 25 respiraciones.',
    salida: 'Baja el cuerpo con control hasta el suelo, deshaz el loto y prepárate para Savasana.',
    mistakes: ['Encoger los hombros hacia las orejas en vez de presionar activamente el suelo hacia abajo.', 'Contener la respiración por el esfuerzo en lugar de mantenerla fluida y contada.'],
    visualization: 'Imagina que todo tu cuerpo flota como una hoja suspendida un instante en el aire antes de que la brisa la deje ir.',
    history: 'Utpluthih significa "elevación" o "salto hacia arriba" y funciona tradicionalmente como el cierre físico de la práctica de asanas antes de la relajación final.',
    energetics: 'Se enseña como el último gran esfuerzo de la práctica: consolida el calor interno generado (tapas) antes de soltarlo por completo en Savasana.',
  },
  Savasana: {
    entrada: 'Túmbate boca arriba, deja que los pies caigan hacia los lados y separa los brazos ligeramente del cuerpo, con las palmas hacia arriba.',
    mantenimiento: 'Cierra los ojos y suelta el control consciente de la respiración y los músculos, permitiendo que el cuerpo se sienta completamente sostenido por el suelo.',
    salida: 'Cuando estés listo, profundiza la respiración, mueve suavemente dedos de manos y pies, y gírate hacia un lado antes de incorporarte a sentado.',
    mistakes: ['Quedarse dormido en vez de mantener una consciencia relajada pero despierta.', 'Salir de la postura abruptamente en lugar de darte una transición gradual hacia el movimiento.'],
    visualization: 'Imagina que cada parte de tu cuerpo se vuelve tan pesada como arena que se hunde lentamente en el suelo, mientras la mente queda tan quieta como la superficie de un lago sin viento.',
    history: 'Savasana, la "postura del cadáver", cierra tradicionalmente toda práctica de hatha yoga como recordatorio de la impermanencia y la necesaria integración del esfuerzo físico en quietud.',
    energetics: 'Se considera el momento en que toda la energía movilizada durante la práctica se asienta e integra en el cuerpo sutil, completando el ciclo de la sesión.',
  },
};

export const asanas = ashtangaSequence.map((pose, index) => ({
  slug: pose.sanskrit
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, ''),
  order: index + 1,
  sanskrit: pose.sanskrit,
  popular: pose.popular,
  description: pose.description,
  image: pose.image,
  sides: Boolean(pose.sides),
  origin: nameOrigins[pose.sanskrit] || null,
  details: details[pose.sanskrit] || null,
  next: index + 1 < ashtangaSequence.length ? ashtangaSequence[index + 1].sanskrit : null,
}));
